### ISSUE TITLE
publish 0.6.1

### ISSUE THREAD

**Issue by thisconnect** [request/aws-sign#12]
I get 

```
 SyntaxError: Duplicate export 'queryStringToSign' (225:32) in node_modules/aws-sign2/index.js
```

This seems already fixed in 
https://github.com/request/aws-sign/commit/03755f299624b43dd30c33611963727f6bb6d877

please `npm publish`

**Comment by Lluvio** [comment]
who could publish it ?

**Comment by jknight12882** [comment]
Would also like to see this published as it's causing `rollup` to crash out

**Comment by quentin-sommer** [comment]
Running into this as wel, @mikeal

**Comment by mikeal** [comment]
@request/contributors who needs to be added to npm to publish this package that doesn't have access yet?

**Comment by nylen** [comment]
@mikeal you might as well just publish it.  you can add me if you like but I'm not really active here anymore.

**Comment by calebboyd** [comment]
This would be most helpful as its currently breaking my build! 👍

**Comment by nylen** [comment]
Per https://www.npmjs.com/package/aws-sign2 ("0.7.0 is the latest of 4 releases") I guess this was done.
