### ISSUE TITLE
Please clarify licensing

### ISSUE THREAD

**Issue by msrb** [request/aws-sign#5]
The repository contains Apache license file, but index.js says "MIT Licensed". Could someone please clarify which parts of the project are licensed under ASL 2.0 and whether index.js is really licensed under MIT?

Thanks

**Comment by hnrtns** [comment]
Not knowing much about the history of this code, this is still a bit confusing. The original licensing statement was 

> Copyright(c) 2010 LearnBoost <dev@learnboost.com> 
> MIT Licensed

Now, it's the same copyright holder but Apache 2.0. I don't know who or what LearnBoost is, but this kind of statement would seem to imply that the original copyright holder (LearnBoost) has now licensed the original code under Apache 2.0. Is that really so? If not, you should clearly state that the license for the original parts is MIT. MIT would also require that you retain the original licensing statement (and strictly taken, that you include the MIT license text somewhere, too).
