### ISSUE TITLE
Exporting 2 different function under same name

### ISSUE THREAD

**Issue by kuebk** [request/aws-sign#7]
I noticed that there are 2 different functions exported under same name, is it on purpose?

https://github.com/mikeal/aws-sign/blob/master/index.js#L126
https://github.com/mikeal/aws-sign/blob/master/index.js#L145

**Comment by tycho01** [comment]
Somehow I think my build just errored because of this:
```
SyntaxError: Duplicate export 'queryStringToSign' (225:32) in PROJECT_PATH\node_modules\aws-sign2\index.js
```

... renaming the former export to `stringToSign` (as I presume would have been the intention) fixed this for me.
